// src/components/constantes.jsx

// Constantes de paginación
export const CLIENTES_PER_PAGE = 10;
export const POLIZAS_PER_PAGE = 10;
export const RECLAMACIONES_PER_PAGE = 10;
export const EMPRESAS_ASEGURADORAS_PER_PAGE = 10;
export const ASESORES_PER_PAGE = 10;
export const COMISIONES_PER_PAGE = 10;

// Clave para almacenar el token de acceso en localStorage
export const ACCESS_TOKEN_KEY = 'insurtech_access_token';

// Opciones de idioma para la configuración
export const LANGUAGE_OPTIONS = [
  { id: 'es', nombre: 'Español' },
  { id: 'en', nombre: 'English' },
  { id: 'fr', nombre: 'Français' },
  { id: 'pt', nombre: 'Português' },
  { id: 'de', nombre: 'Deutsch' },
];

// Opciones de formato de fecha para la configuración
export const DATE_FORMAT_OPTIONS = [
  { id: 'DD/MM/YYYY', nombre: 'DD/MM/YYYY (ej. 31/12/2023)' },
  { id: 'MM/DD/YYYY', nombre: 'MM/DD/YYYY (ej. 12/31/2023)' },
  { id: 'YYYY-MM-DD', nombre: 'YYYY-MM-DD (ej. 2023-12-31)' },
];

// Opciones de símbolo de moneda para la configuración (IDs únicos)
export const CURRENCY_SYMBOL_OPTIONS = [
  { id: 'USD', nombre: '$ (Dólar Americano)' },
  { id: 'VES', nombre: 'Bs (Bolívar Soberano)' },
  { id: 'EUR', nombre: '€ (Euro)' },
  { id: 'PEN', nombre: 'S/ (Sol Peruano)' },
  { id: 'COP', nombre: 'COP (Peso Colombiano)' },
  { id: 'MXN', nombre: 'MXN (Peso Mexicano)' },
  { id: 'CLP', nombre: 'CLP (Peso Chileno)' },
  { id: 'ARS', nombre: 'ARS (Peso Argentino)' },
  { id: 'GBP', nombre: 'GBP (Libra Esterlina)' },
  { id: 'JPY', nombre: 'JPY (Yen Japonés)' },
  { id: 'BRL', nombre: 'R$ (Real Brasileño)' },
  { id: 'CAD', nombre: 'CAD (Dólar Canadiense)' },
  { id: 'AUD', nombre: 'AUD (Dólar Australiano)' },
  { id: 'CNY', nombre: 'CNY (Yuan Chino)' },
  { id: 'INR', nombre: 'INR (Rupia India)' },
  { id: 'RUB', nombre: 'RUB (Rublo Ruso)' },
  { id: 'ZAR', nombre: 'ZAR (Rand Sudafricano)' },
  { id: 'KRW', nombre: 'KRW (Won Surcoreano)' },
  { id: 'SEK', nombre: 'SEK (Corona Sueca)' },
  { id: 'CHF', nombre: 'CHF (Franco Suizo)' },
  { id: 'AED', nombre: 'AED (Dirham EAU)' },
  { id: 'SGD', nombre: 'SGD (Dólar Singapur)' },
  { id: 'NZD', nombre: 'NZD (Dólar Neozelandés)' },
  { id: 'NOK', nombre: 'NOK (Corona Noruega)' },
  { id: 'DKK', nombre: 'DKK (Corona Danesa)' },
  { id: 'PLN', nombre: 'PLN (Zloty Polaco)' },
  { id: 'CZK', nombre: 'CZK (Corona Checa)' },
  { id: 'HUF', nombre: 'HUF (Forint Húngaro)' },
  { id: 'RON', nombre: 'RON (Leu Rumano)' },
  { id: 'BGN', nombre: 'BGN (Lev Búlgaro)' },
  { id: 'HRK', nombre: 'HRK (Kuna Croata)' },
  { id: 'RSD', nombre: 'RSD (Dinar Serbio)' },
  { id: 'TRY', nombre: 'TRY (Lira Turca)' },
  { id: 'EGP', nombre: 'EGP (Libra Egipcia)' },
  { id: 'SAR', nombre: 'SAR (Riyal Saudí)' },
  { id: 'ILS', nombre: 'ILS (Nuevo Shekel Israelí)' },
  { id: 'THB', nombre: 'THB (Baht Tailandés)' },
  { id: 'VND', nombre: 'VND (Dong Vietnamita)' },
  { id: 'PHP', nombre: 'PHP (Peso Filipino)' },
  { id: 'MYR', nombre: 'MYR (Ringgit Malayo)' },
  { id: 'IDR', nombre: 'IDR (Rupia Indonesia)' },
  { id: 'PKR', nombre: 'PKR (Rupia Pakistaní)' },
  { id: 'BDT', nombre: 'BDT (Taka Bangladés)' },
  { id: 'NGN', nombre: 'NGN (Naira Nigeriana)' },
  { id: 'KES', nombre: 'KES (Chelín Keniano)' },
  { id: 'GHS', nombre: 'GHS (Cedi Ghanés)' },
  { id: 'TZS', nombre: 'TZS (Chelín Tanzano)' },
  { id: 'UGX', nombre: 'UGX (Chelín Ugandés)' },
  { id: 'ETB', nombre: 'ETB (Birr Etíope)' },
  { id: 'CDF', nombre: 'CDF (Franco Congoleño)' },
  { id: 'SDG', nombre: 'SDG (Libra Sudanesa)' },
  { id: 'DZD', nombre: 'DZD (Dinar Argelino)' },
  { id: 'MAD', nombre: 'MAD (Dirham Marroquí)' },
  { id: 'TND', nombre: 'TND (Dinar Tunecino)' },
  { id: 'LYD', nombre: 'LYD (Dinar Libio)' },
  { id: 'AOA', nombre: 'AOA (Kwanza Angoleño)' },
  { id: 'MZN', nombre: 'MZN (Metical Mozambicano)' },
  { id: 'ZMW', nombre: 'ZMW (Kwacha Zambiano)' },
  { id: 'ZWL', nombre: 'ZWL (Dólar Zimbabuense)' },
  { id: 'MGA', nombre: 'MGA (Ariary Malgache)' },
  { id: 'XAF', nombre: 'XAF (Franco CFA de África Central)' },
  { id: 'XOF', nombre: 'XOF (Franco CFA de África Occidental)' },
  { id: 'SOS', nombre: 'SOS (Chelín Somalí)' },
  { id: 'YER', nombre: 'YER (Riyal Yemení)' },
  { id: 'SYP', nombre: 'SYP (Libra Siria)' },
  { id: 'IQD', nombre: 'IQD (Dinar Iraquí)' },
  { id: 'JOD', nombre: 'JOD (Dinar Jordano)' },
  { id: 'LBP', nombre: 'LBP (Libra Libanesa)' },
  { id: 'OMR', nombre: 'OMR (Rial Omaní)' },
  { id: 'KWD', nombre: 'KWD (Dinar Kuwaití)' },
  { id: 'QAR', nombre: 'QAR (Riyal Catarí)' },
  { id: 'BHD', nombre: 'BHD (Dinar Bareiní)' },
  { id: 'GEL', nombre: 'GEL (Lari Georgiano)' },
  { id: 'AZN', nombre: 'AZN (Manat Azerbaiyano)' },
  { id: 'AMD', nombre: 'AMD (Dram Armenio)' },
  { id: 'KZT', nombre: 'KZT (Tenge Kazajo)' },
  { id: 'UZS', nombre: 'UZS (Som Uzbeko)' },
  { id: 'KGS', nombre: 'KGS (Som Kirguís)' },
  { id: 'TJS', nombre: 'TJS (Somoni Tayiko)' },
  { id: 'TMT', nombre: 'TMT (Manat Turcomano)' },
  { id: 'AFN', nombre: 'AFN (Afgani Afgano)' },
  { id: 'NPR', nombre: 'NPR (Rupia Nepalí)' },
  { id: 'LKR', nombre: 'LKR (Rupia de Sri Lanka)' },
  { id: 'MMK', nombre: 'MMK (Kyat Birmano)' },
  { id: 'LAK', nombre: 'LAK (Kip Laosiano)' },
  { id: 'KHR', nombre: 'KHR (Riel Camboyano)' },
  { id: 'BN', defaultLanguage: 'ms', nombre: 'Brunéi', defaultCurrencySymbol: 'BND', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TL', defaultLanguage: 'pt', nombre: 'Timor Oriental', defaultCurrencySymbol: 'USD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PG', defaultLanguage: 'en', nombre: 'Papúa Nueva Guinea', defaultCurrencySymbol: 'PGK', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'SB', defaultLanguage: 'en', nombre: 'Islas Salomón', defaultCurrencySymbol: 'SBD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'VU', defaultLanguage: 'bi', nombre: 'Vanuatu', defaultCurrencySymbol: 'VUV', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'FJ', defaultLanguage: 'en', nombre: 'Fiji', defaultCurrencySymbol: 'FJD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TO', defaultLanguage: 'en', nombre: 'Tonga', defaultCurrencySymbol: 'TOP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'WS', defaultLanguage: 'sm', nombre: 'Samoa', defaultCurrencySymbol: 'WST', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'KI', defaultLanguage: 'en', nombre: 'Kiribati', defaultCurrencySymbol: 'AUD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'FM', defaultLanguage: 'en', nombre: 'Micronesia', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'MH', defaultLanguage: 'en', nombre: 'Islas Marshall', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'PW', defaultLanguage: 'en', nombre: 'Palaos', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'NR', defaultLanguage: 'en', nombre: 'Nauru', defaultCurrencySymbol: 'AUD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TV', defaultLanguage: 'en', nombre: 'Tuvalu', defaultCurrencySymbol: 'AUD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'DM', defaultLanguage: 'en', nombre: 'Dominica', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'GD', defaultLanguage: 'en', nombre: 'Granada', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'VC', defaultLanguage: 'en', nombre: 'San Vicente y las Granadinas', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'LC', defaultLanguage: 'en', nombre: 'Santa Lucía', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'KN', defaultLanguage: 'en', nombre: 'San Cristóbal y Nieves', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'AG', defaultLanguage: 'en', nombre: 'Antigua y Barbuda', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BB', defaultLanguage: 'en', nombre: 'Barbados', defaultCurrencySymbol: 'BBD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BS', defaultLanguage: 'en', nombre: 'Bahamas', defaultCurrencySymbol: 'BSD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BZ', defaultLanguage: 'en', nombre: 'Belice', defaultCurrencySymbol: 'BZD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'GY', defaultLanguage: 'en', nombre: 'Guyana', defaultCurrencySymbol: 'GYD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'SR', defaultLanguage: 'nl', nombre: 'Surinam', defaultCurrencySymbol: 'SRD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'HT', defaultLanguage: 'ht', nombre: 'Haití', defaultCurrencySymbol: 'HTG', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'JM', defaultLanguage: 'en', nombre: 'Jamaica', defaultCurrencySymbol: 'JMD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TT', defaultLanguage: 'en', nombre: 'Trinidad y Tobago', defaultCurrencySymbol: 'TTD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CUP', nombre: 'CUP (Peso Cubano)' },
  { id: 'CRC', nombre: 'CRC (Colón Costarricense)' },
  { id: 'HNL', nombre: 'HNL (Lempira Hondureña)' },
  { id: 'NIO', nombre: 'NIO (Córdoba Nicaragüense)' },
  { id: 'PAB', nombre: 'PAB (Balboa Panameño)' },
  { id: 'PYG', nombre: 'PYG (Guaraní Paraguayo)' },
  { id: 'UYU', nombre: 'UYU (Peso Uruguayo)' },
  { id: 'ISK', nombre: 'ISK (Corona Islandesa)' },
  { id: 'LTL', nombre: 'LTL (Litas Lituano)' },
  { id: 'LVL', nombre: 'LVL (Lats Letón)' },
  { id: 'EEK', nombre: 'EEK (Corona Estonia)' },
  { id: 'GIP', nombre: 'GIP (Libra de Gibraltar)' },
  { id: 'JEP', nombre: 'JEP (Libra de Jersey)' },
  { id: 'IMP', nombre: 'IMP (Libra de Isla de Man)' },
  { id: 'FKP', nombre: 'FKP (Libra de las Islas Malvinas)' },
  { id: 'SHP', nombre: 'SHP (Libra de Santa Elena)' },
  { id: 'GGP', nombre: 'GGP (Libra de Guernsey)' },
  { id: 'KMF', nombre: 'KMF (Franco Comorense)' },
  { id: 'MRO', nombre: 'MRO (Ouguiya Mauritana)' },
  { id: 'STD', nombre: 'STD (Dobra de Santo Tomé y Príncipe)' },
  { id: 'SLL', nombre: 'SLL (Leone de Sierra Leona)' },
  { id: 'LRD', nombre: 'LRD (Dólar Liberiano)' },
  { id: 'GMD', nombre: 'GMD (Dalasi Gambiano)' },
  { id: 'GNF', nombre: 'GNF (Franco Guineano)' },
  { id: 'CVE', nombre: 'CVE (Escudo Caboverdiano)' },
  { id: 'DJF', nombre: 'DJF (Franco Yibutiano)' },
  { id: 'ERN', nombre: 'ERN (Nakfa Eritreo)' },
  { id: 'MWK', nombre: 'MWK (Kwacha Malauí)' },
  { id: 'BIF', nombre: 'BIF (Franco Burundés)' },
  { id: 'RWF', nombre: 'RWF (Franco Ruandés)' },
  { id: 'SCR', nombre: 'SCR (Rupia de Seychelles)' },
  { id: 'KID', nombre: 'KID (Dólar de las Islas Cook)' },
  { id: 'TVD', nombre: 'TVD (Dólar de Tuvalu)' },
  { id: 'XPF', nombre: 'XPF (Franco CFP)' },
  { id: 'AWG', nombre: 'AWG (Florín Arubeño)' },
  { id: 'KYD', nombre: 'KYD (Dólar de las Islas Caimán)' },
];

// Opciones de país para la configuración (IDs únicos)
export const COUNTRY_OPTIONS = [
  { id: 'VE', nombre: 'Venezuela', defaultLanguage: 'es', defaultCurrencySymbol: 'VES', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'US', nombre: 'Estados Unidos', defaultLanguage: 'en', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'AR', nombre: 'Argentina', defaultLanguage: 'es', defaultCurrencySymbol: 'ARS', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BO', nombre: 'Bolivia', defaultLanguage: 'es', defaultCurrencySymbol: 'BOB', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CL', nombre: 'Chile', defaultLanguage: 'es', defaultCurrencySymbol: 'CLP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CO', nombre: 'Colombia', defaultLanguage: 'es', defaultCurrencySymbol: 'COP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CR', nombre: 'Costa Rica', defaultLanguage: 'es', defaultCurrencySymbol: 'CRC', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CU', nombre: 'Cuba', defaultLanguage: 'es', defaultCurrencySymbol: 'CUP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'DO', nombre: 'República Dominicana', defaultLanguage: 'es', defaultCurrencySymbol: 'DOP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'EC', nombre: 'Ecuador', defaultLanguage: 'es', defaultCurrencySymbol: 'USD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'SV', nombre: 'El Salvador', defaultLanguage: 'es', defaultCurrencySymbol: 'USD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'GT', nombre: 'Guatemala', defaultLanguage: 'es', defaultCurrencySymbol: 'GTQ', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'HN', nombre: 'Honduras', defaultLanguage: 'es', defaultCurrencySymbol: 'HNL', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'MX', nombre: 'México', defaultLanguage: 'es', defaultCurrencySymbol: 'MXN', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'NI', nombre: 'Nicaragua', defaultLanguage: 'es', defaultCurrencySymbol: 'NIO', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PA', nombre: 'Panamá', defaultLanguage: 'es', defaultCurrencySymbol: 'PAB', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PY', nombre: 'Paraguay', defaultLanguage: 'es', defaultCurrencySymbol: 'PYG', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PE', nombre: 'Perú', defaultLanguage: 'es', defaultCurrencySymbol: 'PEN', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PR', nombre: 'Puerto Rico', defaultLanguage: 'es', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'ES', nombre: 'España', defaultLanguage: 'es', defaultCurrencySymbol: 'EUR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'UY', nombre: 'Uruguay', defaultLanguage: 'es', defaultCurrencySymbol: 'UYU', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CA', nombre: 'Canadá', defaultLanguage: 'en', defaultCurrencySymbol: 'CAD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BR', nombre: 'Brasil', defaultLanguage: 'pt', defaultCurrencySymbol: 'BRL', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'GB', nombre: 'Reino Unido', defaultLanguage: 'en', defaultCurrencySymbol: 'GBP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'FR', nombre: 'Francia', defaultLanguage: 'fr', defaultCurrencySymbol: 'EUR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'DE', nombre: 'Alemania', defaultLanguage: 'de', defaultCurrencySymbol: 'EUR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'IT', nombre: 'Italia', defaultCurrencySymbol: 'EUR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PT', nombre: 'Portugal', defaultCurrencySymbol: 'EUR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'JP', nombre: 'Japón', defaultLanguage: 'ja', defaultCurrencySymbol: 'JPY', defaultDateFormat: 'YYYY-MM-DD' },
  { id: 'AU', nombre: 'Australia', defaultLanguage: 'en', defaultCurrencySymbol: 'AUD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'NZ', nombre: 'Nueva Zelanda', defaultLanguage: 'en', defaultCurrencySymbol: 'NZD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'ZA', nombre: 'Sudáfrica', defaultLanguage: 'en', defaultCurrencySymbol: 'ZAR', defaultDateFormat: 'YYYY-MM-DD' },
  { id: 'IN', nombre: 'India', defaultLanguage: 'en', defaultCurrencySymbol: 'INR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CN', nombre: 'China', defaultLanguage: 'zh', defaultCurrencySymbol: 'CNY', defaultDateFormat: 'YYYY-MM-DD' },
  { id: 'RU', nombre: 'Rusia', defaultLanguage: 'ru', defaultCurrencySymbol: 'RUB', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'SA', nombre: 'Arabia Saudita', defaultLanguage: 'ar', defaultCurrencySymbol: 'SAR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'AE', nombre: 'Emiratos Árabes Unidos', defaultLanguage: 'ar', defaultCurrencySymbol: 'AED', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'SG', nombre: 'Singapur', defaultLanguage: 'en', defaultCurrencySymbol: 'SGD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'KR', nombre: 'Corea del Sur', defaultLanguage: 'ko', defaultCurrencySymbol: 'KRW', defaultDateFormat: 'YYYY.MM.DD' },
  { id: 'SE', nombre: 'Suecia', defaultLanguage: 'sv', defaultCurrencySymbol: 'SEK', defaultDateFormat: 'YYYY-MM-DD' },
  { id: 'CH', nombre: 'Suiza', defaultLanguage: 'de', defaultCurrencySymbol: 'CHF', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'NO', nombre: 'Noruega', defaultCurrencySymbol: 'NOK', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'DK', nombre: 'Dinamarca', defaultCurrencySymbol: 'DKK', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'FI', nombre: 'Finlandia', defaultCurrencySymbol: 'EUR', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'PL', nombre: 'Polonia', defaultCurrencySymbol: 'PLN', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'CZ', nombre: 'República Checa', defaultCurrencySymbol: 'CZK', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'HU', nombre: 'Hungría', defaultCurrencySymbol: 'HUF', defaultDateFormat: 'YYYY.MM.DD.' },
  { id: 'RO', nombre: 'Rumania', defaultCurrencySymbol: 'RON', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'BG', nombre: 'Bulgaria', defaultCurrencySymbol: 'BGN', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'HR', nombre: 'Croacia', defaultCurrencySymbol: 'HRK', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'RS', nombre: 'Serbia', defaultCurrencySymbol: 'RSD', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'TR', nombre: 'Turquía', defaultCurrencySymbol: 'TRY', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'EG', nombre: 'Egipto', defaultCurrencySymbol: 'EGP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'IL', nombre: 'Israel', defaultCurrencySymbol: 'ILS', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TH', nombre: 'Tailandia', defaultCurrencySymbol: 'THB', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'VN', nombre: 'Vietnam', defaultCurrencySymbol: 'VND', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PH', nombre: 'Filipinas', defaultCurrencySymbol: 'PHP', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'MY', nombre: 'Malasia', defaultCurrencySymbol: 'MYR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'ID', nombre: 'Indonesia', defaultCurrencySymbol: 'IDR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PK', nombre: 'Pakistán', defaultCurrencySymbol: 'PKR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BDT', nombre: 'Bangladés', defaultCurrencySymbol: 'BDT', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'NG', nombre: 'Nigeria', defaultCurrencySymbol: 'NGN', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'KE', nombre: 'Kenia', defaultCurrencySymbol: 'KES', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'GH', nombre: 'Ghana', defaultCurrencySymbol: 'GHS', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TZ', nombre: 'Tanzania', defaultCurrencySymbol: 'TZS', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'UG', nombre: 'Uganda', defaultCurrencySymbol: 'UGX', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'ET', nombre: 'Etiopía', defaultCurrencySymbol: 'ETB', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'CD', nombre: 'República Democrática del Congo', defaultLanguage: 'fr', defaultCurrencySymbol: 'CDF', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'SD', nombre: 'Sudán', defaultLanguage: 'ar', defaultCurrencySymbol: 'SDG', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'DZ', nombre: 'Argelia', defaultLanguage: 'ar', defaultCurrencySymbol: 'DZD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'MA', nombre: 'Marruecos', defaultLanguage: 'ar', defaultCurrencySymbol: 'MAD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TN', nombre: 'Túnez', defaultCurrencySymbol: 'TND', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'LY', nombre: 'LYD (Dinar Libio)' },
  { id: 'AOA', nombre: 'AOA (Kwanza Angoleño)' },
  { id: 'MZN', nombre: 'MZN (Metical Mozambicano)' },
  { id: 'ZMW', nombre: 'ZMW (Kwacha Zambiano)' },
  { id: 'ZWL', nombre: 'ZWL (Dólar Zimbabuense)' },
  { id: 'MGA', nombre: 'MGA (Ariary Malgache)' },
  { id: 'XAF', nombre: 'XAF (Franco CFA de África Central)' },
  { id: 'XOF', nombre: 'XOF (Franco CFA de África Occidental)' },
  { id: 'SOS', nombre: 'SOS (Chelín Somalí)' },
  { id: 'YER', nombre: 'YER (Riyal Yemení)' },
  { id: 'SYP', nombre: 'SYP (Libra Siria)' },
  { id: 'IQD', nombre: 'IQD (Dinar Iraquí)' },
  { id: 'JOD', nombre: 'JOD (Dinar Jordano)' },
  { id: 'LBP', nombre: 'LBP (Libra Libanesa)' },
  { id: 'OMR', nombre: 'OMR (Rial Omaní)' },
  { id: 'KWD', nombre: 'KWD (Dinar Kuwaití)' },
  { id: 'QAR', nombre: 'QAR (Riyal Catarí)' },
  { id: 'BHD', nombre: 'BHD (Dinar Bareiní)' },
  { id: 'GE', nombre: 'Georgia', defaultLanguage: 'ka', defaultCurrencySymbol: 'GEL', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'AZ', nombre: 'Azerbaiyán', defaultLanguage: 'az', defaultCurrencySymbol: 'AZN', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'AM', nombre: 'Armenia', defaultLanguage: 'hy', defaultCurrencySymbol: 'AMD', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'KZ', nombre: 'Kazajistán', defaultLanguage: 'kk', defaultCurrencySymbol: 'KZT', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'UZ', nombre: 'Uzbekistán', defaultCurrencySymbol: 'UZS', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'KG', nombre: 'Kirguistán', defaultCurrencySymbol: 'KGS', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'TJ', nombre: 'Tayikistán', defaultCurrencySymbol: 'TJS', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'TM', nombre: 'Turkmenistán', defaultCurrencySymbol: 'TMT', defaultDateFormat: 'DD.MM.YYYY' },
  { id: 'AF', nombre: 'Afganistán', defaultCurrencySymbol: 'AFN', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'NP', nombre: 'Nepal', defaultCurrencySymbol: 'NPR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'LK', nombre: 'Sri Lanka', defaultCurrencySymbol: 'LKR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'MM', nombre: 'Myanmar (Birmania)', defaultCurrencySymbol: 'MMK', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'LA', nombre: 'Laos', defaultCurrencySymbol: 'LAK', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'KH', nombre: 'Camboya', defaultCurrencySymbol: 'KHR', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BN', defaultLanguage: 'ms', nombre: 'Brunéi', defaultCurrencySymbol: 'BND', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TL', defaultLanguage: 'pt', nombre: 'Timor Oriental', defaultCurrencySymbol: 'USD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'PG', defaultLanguage: 'en', nombre: 'Papúa Nueva Guinea', defaultCurrencySymbol: 'PGK', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'SB', defaultLanguage: 'en', nombre: 'Islas Salomón', defaultCurrencySymbol: 'SBD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'VU', defaultLanguage: 'bi', nombre: 'Vanuatu', defaultCurrencySymbol: 'VUV', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'FJ', defaultLanguage: 'en', nombre: 'Fiji', defaultCurrencySymbol: 'FJD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TO', defaultLanguage: 'en', nombre: 'Tonga', defaultCurrencySymbol: 'TOP', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'WS', defaultLanguage: 'sm', nombre: 'Samoa', defaultCurrencySymbol: 'WST', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'KI', defaultLanguage: 'en', nombre: 'Kiribati', defaultCurrencySymbol: 'AUD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'FM', defaultLanguage: 'en', nombre: 'Micronesia', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'MH', defaultLanguage: 'en', nombre: 'Islas Marshall', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'PW', defaultLanguage: 'en', nombre: 'Palaos', defaultCurrencySymbol: 'USD', defaultDateFormat: 'MM/DD/YYYY' },
  { id: 'NR', defaultLanguage: 'en', nombre: 'Nauru', defaultCurrencySymbol: 'AUD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TV', defaultLanguage: 'en', nombre: 'Tuvalu', defaultCurrencySymbol: 'AUD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'DM', defaultLanguage: 'en', nombre: 'Dominica', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'GD', defaultLanguage: 'en', nombre: 'Granada', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'VC', defaultLanguage: 'en', nombre: 'San Vicente y las Granadinas', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'LC', defaultLanguage: 'en', nombre: 'Santa Lucía', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'KN', defaultLanguage: 'en', nombre: 'San Cristóbal y Nieves', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'AG', defaultLanguage: 'en', nombre: 'Antigua y Barbuda', defaultCurrencySymbol: 'XCD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BB', defaultLanguage: 'en', nombre: 'Barbados', defaultCurrencySymbol: 'BBD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BS', defaultLanguage: 'en', nombre: 'Bahamas', defaultCurrencySymbol: 'BSD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'BZ', defaultLanguage: 'en', nombre: 'Belice', defaultCurrencySymbol: 'BZD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'GY', defaultLanguage: 'en', nombre: 'Guyana', defaultCurrencySymbol: 'GYD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'SR', defaultLanguage: 'nl', nombre: 'Surinam', defaultCurrencySymbol: 'SRD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'HT', defaultLanguage: 'ht', nombre: 'Haití', defaultCurrencySymbol: 'HTG', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'JM', defaultLanguage: 'en', nombre: 'Jamaica', defaultCurrencySymbol: 'JMD', defaultDateFormat: 'DD/MM/YYYY' },
  { id: 'TT', defaultLanguage: 'en', nombre: 'Trinidad y Tobago', defaultCurrencySymbol: 'TTD', defaultDateFormat: 'DD/MM/YYYY' },
];

// Clave de licencia "maestra" para la validación básica en frontend.
export const MASTER_LICENSE_KEY = 'KEYLA-ALEIKA-HIJAS-2025'; // <-- ¡CORRECCIÓN CRÍTICA AQUÍ!

// Elementos de la barra de navegación
export const NAV_ITEMS = [
  { name: 'Dashboard', id: 'dashboard' },
  { name: 'Configuración', id: 'configuracion' },
  { name: 'Clientes', id: 'clientes' },
  { name: 'Empresas Aseguradoras', id: 'empresas_aseguradoras' }, // <-- CAMBIO DE ORDEN
  { name: 'Asesores', id: 'asesores' }, // <-- CAMBIO DE ORDEN
  { name: 'Polizas', id: 'polizas' }, // <-- CAMBIO DE ORDEN
  { name: 'Reclamaciones', id: 'reclamaciones' }, // <-- CAMBIO DE ORDEN
  { name: 'Comisiones', id: 'comisiones' },
];

// Opciones para el Select de Tipo de Póliza (para PolizaForm y PolizaList)
export const TIPO_POLIZA_OPTIONS = [
  { value: 'Salud', label: 'Salud' },
  { value: 'Vida', label: 'Vida' },
  { value: 'Vehiculo', label: 'Vehículo' },
  { value: 'Hogar', label: 'Hogar' },
  { value: 'Viaje', label: 'Viaje' },
  { value: 'Otros', label: 'Otros' },
];

// Opciones para el Select de Estado de Póliza (para PolizaForm y PolizaList)
export const ESTADO_POLIZA_OPTIONS = [
  { value: 'Activa', label: 'Activa' },
  { value: 'Pendiente', label: 'Pendiente' },
  { value: 'Vencida', label: 'Vencida' },
  { value: 'Cancelada', label: 'Cancelada' },
];
export const ESTADO_RECLAMACION_OPTIONS = [
  { value: 'Pendiente', label: 'Pendiente' },
  { value: 'Aprobada', label: 'Aprobada' },
  { value: 'Rechazada', label: 'Rechazada' },
  { value: 'En Proceso', label: 'En Proceso' }, // ¡CRÍTICO! Asegurar coincidencia exacta
  { value: 'Cerrada', label: 'Cerrada' },
];

// Opciones para el Select de Estatus de Pago de Comisión
export const ESTATUS_PAGO_OPTIONS = [
  { value: 'Pendiente', label: 'Pendiente' },
  { value: 'Pagado', label: 'Pagado' },
  { value: 'Anulado', label: 'Anulado' },
];

// Opciones para el Select de Tipo de Comisión
export const TIPO_COMISION_OPTIONS = [
  { value: 'Venta Nueva', label: 'Venta Nueva' },
  { value: 'Renovación', label: 'Renovación' },
  { value: 'Servicio Adicional', label: 'Servicio Adicional' },
];
